[workspace]
name = "random-predictor"
version = "0.1.0"
description = "Random Predictor baseline - generates random predictions for benchmarking"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "3.11.*"
numpy = ">=1.24"
pandas = ">=2.0"
typer = ">=0.9"

[pypi-dependencies]
abdev-core = { path = "../../libs/abdev_core", editable = true }
random-predictor = { path = ".", editable = true }

[environments]
default = []
dev = ["dev"]

[feature.dev.dependencies]
pytest = ">=7.0"
ruff = ">=0.1"

[feature.dev.tasks]
lint = "ruff check src && ruff format --check src"
test = "pytest tests -v"
