[workspace]
name = "tap-linear"
version = "0.1.0"
description = "TAP Linear baseline - Ridge regression on TAP features"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "3.11.*"
numpy = ">=1.24"
pandas = ">=2.0"
scikit-learn = ">=1.3"

[pypi-dependencies]
abdev-core = { path = "../../libs/abdev_core", editable = true }
tap-linear = { path = ".", editable = true }

[tasks]
predict = "python -m tap_linear.predict"
eval = "pixi run -C ../../evaluation score --pred ../../predictions/GDPa1_cross_validation/tap_linear/tap_linear.csv --truth ../../data/GDPa1_v1.2_20250814.csv --dataset GDPa1_cross_validation --model-name tap_linear"
lint = "ruff check src && ruff format --check src"
test = "pytest tests -v"

[environments]
default = []
dev = ["dev"]

[feature.dev.dependencies]
pytest = ">=7.0"
ruff = ">=0.1"

