[workspace]
name = "tap-linear"
version = "0.1.0"
description = "TAP Linear baseline - Ridge regression on TAP features"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "3.11.*"
numpy = ">=1.24"
pandas = ">=2.0"
scikit-learn = ">=1.3"
typer = ">=0.9"

[pypi-dependencies]
abdev-core = { path = "../../libs/abdev_core", editable = true }
tap-linear = { path = ".", editable = true }

[environments]
default = []
dev = ["dev"]

[feature.dev.dependencies]
pytest = ">=7.0"
ruff = ">=0.1"

[feature.dev.tasks]
# Development tasks only - orchestrator will call train/predict directly
lint = "ruff check src && ruff format --check src"
test = "pytest tests -v"
