[workspace]
name = "deepviscosity"
version = "0.1.0"
description = "DeepViscosity baseline - viscosity predictions"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "linux-64"]

[dependencies]
python = "3.11.*"
pandas = ">=2.0"

[pypi-dependencies]
abdev-core = { path = "../../libs/abdev_core", editable = true }
deepviscosity = { path = ".", editable = true }

[tasks]
predict = "python -m deepviscosity.predict"
lint = "ruff check src && ruff format --check src"
test = "pytest tests -v"

[environments]
default = []
dev = ["dev"]

[feature.dev.dependencies]
pytest = ">=7.0"
ruff = ">=0.1"

