exclude: ".*(csv|pdb)$"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Fast Python linter and formatter - replaces flake8, isort, and black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      # Run the Ruff linter
      - id: ruff-check
        args: ["--fix", "--exit-non-zero-on-fix"]
      # Run the Ruff formatter
      - id: ruff-format
