[workspace]
name = "antifold"
version = "0.1.0"
description = "AntiFold baseline - antibody stability predictions"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "3.11.*"
pandas = ">=2.0"

[pypi-dependencies]
abdev-core = { path = "../../libs/abdev_core", editable = true }
antifold = { path = ".", editable = true }

[tasks]
predict = "python -m antifold.predict"
lint = "ruff check src && ruff format --check src"
test = "pytest tests -v"

[environments]
default = []
dev = ["dev"]

[feature.dev.dependencies]
pytest = ">=7.0"
ruff = ">=0.1"

