name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-projects:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - evaluation
          - baselines/tap_linear
          - baselines/tap_single_features
          - baselines/aggrescan3d
          - baselines/antifold
          - baselines/saprot_vh
          - baselines/deepviscosity
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.2
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      
      - name: Check lockfile
        if: startsWith(matrix.project, 'baselines/')
        working-directory: ${{ matrix.project }}
        run: pixi lock --check
      
      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: pixi install
      
      - name: Lint code
        working-directory: ${{ matrix.project }}
        run: pixi run lint || echo "Linting not configured or failed"
        continue-on-error: true
      
      - name: Run tests
        working-directory: ${{ matrix.project }}
        run: pixi run test || echo "Tests not configured or no tests yet"
        continue-on-error: true
  
  integration-test:
    runs-on: ubuntu-latest
    needs: test-projects
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.2
        with:
          cache: true
      
      - name: Test evaluation CLI
        working-directory: evaluation
        run: |
          pixi install
          pixi run validate --pred ../tests/baseline_results/predictions/GDPa1/TAP/TAP\ -\ linear\ regression.csv || echo "Validation test - expected result"
      
      - name: Verify structure
        run: |
          echo "Checking directory structure..."
          test -d baselines/tap_linear && echo "✓ baselines/tap_linear exists"
          test -d evaluation && echo "✓ evaluation exists"
          test -d libs/abdev_core && echo "✓ libs/abdev_core exists"
          test -d data/schema && echo "✓ data/schema exists"
          echo "Structure verification complete"

